export const spouseAndGuardianDefaults = {
  husband: {
    prefix: "SH",
    firstName: "",
    middleName: "",
    lastName: "",
    occupation: {
      type: "service",
      reason: "",
      post: "",
      department: "",
      place: "",
      salary: "",
      businessType: "",
      businessPlace: "",
      ownershipType: "",
    },
    satsangi: "satsangi",
    inititationDetails: {
      initiatedBy: "",
      initiatedFrom: "dayalbagh",
      dateOfInitiation: null,
      placeOfInitiation: "",
    },
  },
  wife: {
    prefix: "SMT",
    firstName: "",
    middleName: "",
    lastName: "",
    satsangi: "satsangi",
    inititationDetails: {
      initiatedBy: "",
      initiatedFrom: "dayalbagh",
      dateOfInitiation: null,
      placeOfInitiation: "",
    },
  },
  guardian: {
    prefix: "SH",
    firstName: "",
    middleName: "",
    lastName: "",
    occupation: {
      type: "service",
      reason: "",
      post: "",
      department: "",
      place: "",
      salary: "",
      businessType: "",
      businessPlace: "",
      ownershipType: "",
    },
    satsangi: "satsangi",
    inititationDetails: {
      initiatedBy: "",
      initiatedFrom: "dayalbagh",
      dateOfInitiation: null,
      placeOfInitiation: "",
    },
  },
};
