export const parentsDetailsDefaults = {
  father: {
    prefix: "SH",
    firstName: "",
    middleName: "",
    lastName: "",
    occupation: {
      type: "service",
      reason: "",
      post: "",
      department: "",
      place: "",
      salary: "",
      businessType: "",
      businessPlace: "",
      ownershipType: "",
    },
    satsangi: "satsangi",
    initiationDetails: {
      initiatedBy: "",
      initiatedFrom: "dayalbagh",
      dateOfInitiation: null,
      placeOfInitiation: "",
    },
  },
  mother: {
    prefix: "SMT",
    firstName: "",
    middleName: "",
    lastName: "",
    occupation: {
      type: "unemployed",
      reason: "",
      post: "",
      department: "",
      place: "",
      salary: "",
      businessType: "",
      businessPlace: "",
      ownershipType: "",
    },
    satsangi: "satsangi",
    initiationDetails: {
      initiatedBy: "",
      initiatedFrom: "dayalbagh",
      dateOfInitiation: null,
      placeOfInitiation: "",
    },
  },
};
